### ISSUE TITLE
Provision the first Node 10.0.21.7 with RHCOS/RHEL OS

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#11]

**Comment by YonatanGolick** [comment]
Managed to provision RHEL 8.3 on the first node.
A quick guide on how to:
**On the foreman server** 
1. Copied the rhel-8.3-ppc64le-dvd.iso file into the foreman server.
2. Mounted the file to get the following directory
`mount -o loop installation_directory/rhel-8.3-ppc64le-dvd.iso /installation_directory/rhelfiles` 
![mounted_dvd_iso](https://user-images.githubusercontent.com/74144741/102907055-2909ac80-447e-11eb-8fc2-7b5206ec7869.png)
3. Enter the directory and run the next command to start an http server on with the content of the directory
python3 -m http.server --b 10.30.4.1
**On the SOL console (indise the BMC System Management interface)**
1. Run the following command to asign private ip address to the node
```
ip addr add 10.30.4.20/24 dev enp1s0f0
ip link set enp1s0f0 up
```
2. Enter to the petitboot menu and press n
3. Copy the next url's into their designated spots
```
Kernel - http://10.30.4.1:8000/ppc/ppc64/vmlinuz
Initrd - http://10.30.4.1:8000/ppc/ppc64/initrd.img
boot arguments - repo=http://10.30.4.1:8000/ root=live:http://10.30.4.1:8000/images/install.img ipv6.disable=1 console=hvc0 console=tty0 ifname=enp1s0f0:50:6b:4b:fb:4e:52 ip=10.30.4.20::10.30.4.1:24:bu-21-7:enp1s0f0:none
```
![Petitboot Provisioning from URLs manually](https://user-images.githubusercontent.com/74144741/102908021-881bf100-447f-11eb-9766-5220cab1182f.png)
4. Now chose the user item in the main petitboot menu 
5. Let the node reboot itself and there you go 
![red_hat_os_proof](https://user-images.githubusercontent.com/74144741/102908252-daf5a880-447f-11eb-9ee7-0f3bae9b1e92.png)

**Comment by YonatanGolick** [comment]
Now we have another problem - the OS is not persistent (when we reboot the system it goes back to the petitboot minimal os..
Working on it.

**Comment by Rmaabari** [comment]
Node is Provisioned with a permanent RHEL 8.3
