### ISSUE TITLE
Handle the network issues on the 2 unready nodes

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#12]

**Comment by YonatanGolick** [comment]
Hey @naved001,
After successfully provisioning the OS on the bu-21-7 node tried to provision an OS on the other 2 nodes but with no luck.
In the bu-21-5 we got a network issue - couldn't get the NIC working. On this issue #4 you said there are still some network issues you are working on is that still ongoing ?
In the bu-21-6 we cant even ping the node.

Can you please give us an update on this 2 nodes status ?

**Comment by Rmaabari** [comment]
Hi Naved,
quick question please, does the nodes supports LPAR (Logical Partition)? 
Thanks in advance.

**Comment by naved001** [comment]
Hey guys, 

I am tracking the networking issue with the 2 nodes here: https://github.com/CCI-MOC/ops-issues/issues/89

I am not sure what LPAR is and if that is supported.

**Comment by Rmaabari** [comment]
Hi Naved thanks for the replay.
we are encountering some HDD issues on node7, seems something we messed up during our previous provisions.
is there any option from your side to format the node and get it back to the original state?

**Comment by etnir** [comment]
Hi @naved001 .
Can you share any update regarding this issue? 
It is blocking our progress.

Thanks in advance

**Comment by naved001** [comment]
Hi @etnir 

Apologies for the delay. We are waiting for someone to go out to the data center to check the cables on the 2 problem nodes. That *may* happen this Saturday or Sunday.

cc: @msdisme

**Comment by etnir** [comment]
Hi @naved001 , any update on this?

Thanks in advance

**Comment by naved001** [comment]
Update:

We are blocked on the data center visit to fix the other 2 nodes. First step is to diagnose what's wrong (bad switchport or bad cable or bad nic, or something else entirely) and then take appropriate action based on the diagnosis. The next data center visit will happen on the 16th and then we'll have more details.

**Comment by naved001** [comment]
Hi guys,

Both of the nics on bu-21-5 and bu-21-6 are now working.
```
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enP5p1s0f0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 08:94:ef:80:62:1b brd ff:ff:ff:ff:ff:ff
3: enP5p1s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 08:94:ef:80:62:1c brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 1000
    link/ether 50:6b:4b:fb:4e:0a brd ff:ff:ff:ff:ff:ff
    inet 10.30.4.22/24 scope global enp1s0f0
       valid_lft forever preferred_lft forever
6: enp1s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 1000
    link/ether 50:6b:4b:fb:4e:0b brd ff:ff:ff:ff:ff:ff
    inet 10.30.5.5/24 scope global enp1s0f1
       valid_lft forever preferred_lft forever
/ # ping 10.30.4.1
PING 10.30.4.1 (10.30.4.1): 56 data bytes
64 bytes from 10.30.4.1: seq=0 ttl=64 time=1.704 ms
^C
--- 10.30.4.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.704/1.704/1.704 ms
/ # ping 10.30.5.1
PING 10.30.5.1 (10.30.5.1): 56 data bytes
64 bytes from 10.30.5.1: seq=0 ttl=64 time=1.651 ms
64 bytes from 10.30.5.1: seq=1 ttl=64 time=1.560 ms
^C
--- 10.30.5.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 1.560/1.605/1.651 ms
/ #
```

```
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enP5p1s0f0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 08:94:ef:80:62:5a brd ff:ff:ff:ff:ff:ff
3: enP5p1s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 08:94:ef:80:62:5b brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: enp1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 1000
    link/ether ec:0d:9a:82:de:9e brd ff:ff:ff:ff:ff:ff
    inet 10.30.4.6/24 scope global enp1s0f0
       valid_lft forever preferred_lft forever
6: enp1s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 1000
    link/ether ec:0d:9a:82:de:9f brd ff:ff:ff:ff:ff:ff
    inet 10.30.5.6/24 scope global enp1s0f1
       valid_lft forever preferred_lft forever
/ # ping 10.30.4.1
PING 10.30.4.1 (10.30.4.1): 56 data bytes
64 bytes from 10.30.4.1: seq=0 ttl=64 time=1.569 ms
^C
--- 10.30.4.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.569/1.569/1.569 ms
/ # ping 10.30.5.1
PING 10.30.5.1 (10.30.5.1): 56 data bytes
64 bytes from 10.30.5.1: seq=0 ttl=64 time=2.143 ms
64 bytes from 10.30.5.1: seq=1 ttl=64 time=3.143 ms
^C
--- 10.30.5.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 2.143/2.643/3.143 ms
```

**Comment by YonatanGolick** [comment]
Hey @naved001, We have the same issue again on the bu-21-6 node. 
Trying to give an ip address to several different interfaces none of them work.
Can you check this out, please?

**Comment by YonatanGolick** [comment]
Hi @naved001, I have a problem with the network in the bu-21-6 node.
The network is working/not working randomly. 
After configuring the IP address and activating the network interface there is no connection to the network (using 10.30.5.6 IP).
Each time I'm trying different nic's so the problem is not related to a specific nic.
One thing to mention is that the nic has a NO-CARRIER label when it doesn't work.
After a couple of hours doing the exact same procedure, the network suddenly works and then again the same thing.
This is a real voodoo situation and I would like to try to solve it for good because it stops the flow of the work.

**Comment by YonatanGolick** [comment]
![image](https://user-images.githubusercontent.com/74144741/107212962-65826f00-6a10-11eb-8a38-514b3fd1dcdb.png)

**Comment by naved001** [comment]
Hi @YonatanGolick I'll take a look and get it resolved.

> This is a real voodoo situation and I would like to try to solve it for good

I feel the same way about it to be honest. I'll be opening a ticket with IBM in case we might have to replace the NIC itself.

**Comment by naved001** [comment]
Hi @YonatanGolick it seems to be fixed for now. In the meanwhile we are looking into swapping this node with another once, or changing the nics/cables.

**Comment by YonatanGolick** [comment]
Hey @naved001, it seems that the network issues are still happening every other reboot. Can we proceed with the nics/cables switching? The odd thing is that it happens in both 10.0.21.5 and 10.0.21.6 nodes.

**Comment by naved001** [comment]
I am working on setting up 2 other power9 nodes for you (21.8 and 21.10), I'll update this thread once those nodes are ready.

**Comment by YonatanGolick** [comment]
@naved001, great! The firmware is going to be the latest?

**Comment by naved001** [comment]
Updated information here:

https://github.com/CCI-MOC/rubicon-issues/issues/30#issuecomment-787987930

**Comment by naved001** [comment]
@YonatanGolick After swapping the cables, the 2 nodes are now working again. I have given you access to 2 more nodes: bu-21-5 (10.0.21.5) and bu-21-6 (10.0.21.6). That's a total of 5 nodes.

**Comment by YonatanGolick** [comment]
@naved001, Great news thank you! one thing is missing, I don't have the credentials to access these nodes. Tried both hil user and root with the passwords we had.
