### ISSUE TITLE
Power on the foreman server 

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#14]
Hey @naved001,
Trying to connect to the foreman server (129.10.5.144) but with no luck.
Trying to ping it as well but the request timed out.
Suspecting the server is powered off, can you help us with that ?

**Comment by naved001** [comment]
Yes, looks like there was a power outage at the data center where we are hosted and that caused a bunch of stuff to turn off. I have powered on the foreman server.
