### ISSUE TITLE
No route to host when trying to access bu-21-6 BMC web interface

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#17]

**Comment by naved001** [comment]
The system is back up now. I was able to get to the BMC web interface.

**Comment by idanlv** [comment]
@naved001 - can you share what was the issue?

**Comment by naved001** [comment]
@idanlv The BMC was unreachable for me too. I thought the BMC might have lost its IP configuration, so I looked into the dhcp lease file but didn't find any IP from the dynamic range. So I power cycled the server from the PDU and then the BMC came back online on the statically configured IP. I am not sure what caused the BMC to stop responding in the first place.

**Comment by idanlv** [comment]
Thank you for adding more input.
