### ISSUE TITLE
Questions about the architecture of the OCP installation

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#2]
hey @naved001, As we discussed in the meeting here are the questions we have:

1. Where does all of the network configuration taking place ? We need access to the DHCP/DNS server or we need someone whos got access, who will set up the ip addresses to the nodes ?
2. CPU architecture - is it x86_64 ? If not what is the architecture?
3. Network interface must be at least 1-GB for the routable baremetal network do we have it ?
4. UEFI - We need it to be boot on, how and who will configure it ?
5. According to the installation process we are using link here we need 2 networks, one baremetal network that is connected to the internet, and provisioning network. How can we reach this configuration from our current status.

**Comment by naved001** [comment]
I don't know if you are following the IPI or UPI docs, but  [IPI installation](https://openshift-kni.github.io/baremetal-deploy/4.6/Deployment.html#node-requirements_ipi-install-prerequisites) is **not supported** for any other architectures besides `x86_64`.


> 1. Where does all of the network configuration taking place ? We need access to the DHCP/DNS server or we need someone whos got access, who will set up the ip addresses to the nodes ?

That may depend on the type of installation you are doing. The 2 interfaces of the nodes are on 2 different VLANS that are for exclusive use for this project. You could run your own dhcp/dns server for those 2 VLANS (maybe on the foreman host).

> CPU architecture - is it x86_64 ? If not what is the architecture? 

The 3 power9 servers are `ppc64le`. 

> Network interface must be at least 1-GB for the routable baremetal network do we have it ?

Yes, they have 40Gig nics

> UEFI - We need it to be boot on, how and who will configure it ?

You have full access to the server's BMC. That can be configured from there.

> According to the installation process we are using link here

Can you tell us what installation process you are using? 

>  we need 2 networks, one baremetal network that is connected to the internet, and provisioning network. How can we reach this configuration from our current status.

If the baremetal network needs to route to internet, then you can setup the foreman host to do that for you. @larsks does the baremetal network **need** to be a public network?

**Comment by larsks** [comment]
@naved001 the systems need an outbound route to the internet in order to pull container images, etc. That doesn't require a public network (i.e., a NAT gateway would work just fine).

To be useful, there probably needs to be some sort of inbound access as well (for providing access to services hosted on the cluster). That's typically provided via a loadbalancer of some sort, which with the baremetal IPI cluster is provided by the cluster itself, but the story may be different for a UPI install.

**Comment by naved001** [comment]
Related: #4

**Comment by naved001** [comment]
Hi @YonatanGolick ,

Did I answer your question? This is the end of our sprint and I am marking things as done or not, which is why I ask.

Thanks!

**Comment by YonatanGolick** [comment]
Hey @naved001, 
Yes thank you for all the help for now we are good.
