### ISSUE TITLE
Create RHCOS machines

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#24]
Working on creating the RHCOS machines with the ignition files. encountered some issues with the installation, working on it.

**Comment by YonatanGolick** [comment]
Having some issues with a complete installation of RHCOS on the bootstrap server.
Here are the steps taken to what we accomplished so far:
1. Entered the petitboot menu as we did in the last installations.

![image](https://user-images.githubusercontent.com/74144741/106595326-1219a800-655c-11eb-9668-a2de94fb0115.png)

2. Booted the system and got into a maintenance mode

3. Downloaded the image & the bootstrap ignition file
 `curl http://10.30.5.1:8080/bootstrap.ign -o bootstrap.ign`
 `curl http://10.30.5.1:8080/rhcos-4.6.8-ppc64le-metal.ppc64le.raw.gz -o rhcos-4.6.8-ppc64le-metal.ppc64le.raw.gz`

4. Created a sig file for the image
`gpg --quick-generate-key 0`
`gpg --detach-sign rhcos-4.6.8-ppc64le-metal.ppc64le.raw.gz`

5. Ran the installation command with arguments attached
![image](https://user-images.githubusercontent.com/74144741/106595969-0f6b8280-655d-11eb-9c33-07336f1d7943.png)

**Comment by YonatanGolick** [comment]
Saw this issue as well and tried to work as they suggested
https://forums.mageia.org/en/viewtopic.php?f=7&t=8735
But it didn't solve the problem as well.

**Comment by YonatanGolick** [comment]
Hey @naved001, we would like to use the MOC subscription to open a ticket to RH's support about this issue. Can you help us with that?

**Comment by larsks** [comment]
@msdisme can you see about adding @YonatanGolick as a contact for BU?

**Comment by YonatanGolick** [comment]
Any update guys? @larsks @msdisme

**Comment by msdisme** [comment]
@YonatanGolick you should receive an email asking you to login/create account - username is yonatanrubicone

**Comment by YonatanGolick** [comment]
@msdisme Didn't get the email .. any chance to resend it?

**Comment by idanlv** [comment]
@msdisme @larsks 
Hi - any updates?
We need the support account to report several issues.

**Comment by msdisme** [comment]
@YonatanGolick just confirming your email is yonatangolick@rubicone.co.il?  Your account name is yonatanrubicone - I do not see a way to resend it.  Two things, ,can you login in with that and a forgot password - at the same time I will open a query with support to see if they are able to resolve it.

**Comment by YonatanGolick** [comment]
@msdisme I press forgot password and now I can open tickets as a MOC member. thanks, guys!
