### ISSUE TITLE
Get updated firmware images for the BMC + the server itself

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#29]

**Comment by YonatanGolick** [comment]
Hey @naved001, can you help us find updated firmware images for the power9 systems? We have encountered some issues while trying to install RHCOS on the nodes and it might be because of the old hardware.

**Comment by YonatanGolick** [comment]
Found this ftp server ftp://170.225.15.34/ecc/sar/CMA/SFA/
Managed to update the BMC firmware.
Tried several different server images none of them worked, currently, the problem is that there is no working image for the server and I can't turn on the server.

**Comment by YonatanGolick** [comment]
After degrading the BMC firmware back to the original I was successfully able to update the server firmware.
Updated the firmware from v2.0.10 to v2.4

**Comment by naved001** [comment]
Hey @YonatanGolick sorry this issue slipped out of my mind. I am glad you found the right firmware though.

Where did you get the firmware v.24 from?

**Comment by YonatanGolick** [comment]
@naved001 just go to https://www.ibm.com/support/fixcentral put the model number and chose the newest firmware for it :)
