### ISSUE TITLE
Configure the Network in the system

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#3]
Add details about the network here

**Comment by YonatanGolick** [comment]
hey @naved001,
So we had a couple of attempts to provision an OS on the bu-21-7 host.
1. With the help of the foreman server UI with your instructions from #4 , configured everything and tried to build the host but no actions occurred on the node.
2. Tried to provision with the petitboot itself with this doc https://www.ibm.com/support/knowledgecenter/linuxonibm/liabw/liabppetitbootadvanced.html 
3. Another attempt was with this option https://community.theforeman.org/t/netbooting-ibm-power9-via-petitboot/17104

None of them worked.
The problem is we have no connectivity to the foreman host (where all the ISO and configuration files are sitting).
We are not sure how but we think we need to connect the foreman to the private network of the node. Can you help us with that ?

**Comment by naved001** [comment]
@YonatanGolick can I take a look at the node? (I want to power cycle it).

**Comment by YonatanGolick** [comment]
> @YonatanGolick can I take a look at the node? (I want to power cycle it).

Yes for sure, See you at the meeting in 20 minutes ?

**Comment by naved001** [comment]
> See you at the meeting in 20 minutes ?
yes!
