### ISSUE TITLE
BMC servers are unreachable

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#30]
Hey @naved001,
Trying to ssh to the 10.0.21.5 and 10.0.21.6 servers but can't reach them. cant open the BMC web interface of these servers as well.
Haven't done anything unusual on those servers.
10.0.21.7 is working fine.
Can you take a look, please?

**Comment by naved001** [comment]
Hi @YonatanGolick 

Sorry I forgot to update the other ticket. 

I have replaced `10.0.21.5` and `10.0.21.6` with `10.0.21.1` and `10.0.21.10`.

You should be able to reach those. the BMC login credentials are:

username: `hil`
password: `H1lu$ers`

I have configured their networking so they are connected to the right VLANs.

**Comment by joachimweyl** [comment]
Closing all rubicon-issues.
