### ISSUE TITLE
api-server not created when provisioning master node

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#31]

**Comment by YonatanGolick** [comment]
After provisioning the bootstrap and master nodes, I ssh to both servers and see with `podman images` command all the images that were supposed to be pulled.
![image](https://user-images.githubusercontent.com/74144741/110782478-db783100-826f-11eb-9a88-7c29ca4e2f58.png)

The next step is the `./openshift-install --dir=<installation_directory> wait-for bootstrap-complete \ 
    --log-level=info` command that gives us an error:
![image](https://user-images.githubusercontent.com/74144741/110782628-14180a80-8270-11eb-8500-11e0732497e8.png)

It seems that the api-server on the master node is not responding.

**Comment by YonatanGolick** [comment]
https://access.redhat.com/support/cases/#/case/02901856

**Comment by joachimweyl** [comment]
Closing all rubicon-issues.
