### ISSUE TITLE
AIO OCP4 Deployment

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#32]
This issue shows the progress of our main objective - Deploying OpenShift 4

**Comment by YonatanGolick** [comment]
[Configure the Network in the system](https://github.com/CCI-MOC/rubicon-issues/issues/3)

**Comment by YonatanGolick** [comment]
[Network & Forman information](https://github.com/CCI-MOC/rubicon-issues/issues/4)

**Comment by YonatanGolick** [comment]
[Install & Configure a foreman server on the foreman](https://github.com/CCI-MOC/rubicon-issues/issues/5)

**Comment by YonatanGolick** [comment]
[Get the ISO file for RHEL/RHCOS that suits the ppc architecture](https://github.com/CCI-MOC/rubicon-issues/issues/6)

**Comment by YonatanGolick** [comment]
[investigate how the DHCP works on the Foremen](https://github.com/CCI-MOC/rubicon-issues/issues/7)

**Comment by YonatanGolick** [comment]
[Password request for root user on both BMC & foreman servers.](https://github.com/CCI-MOC/rubicon-issues/issues/8)

**Comment by YonatanGolick** [comment]
[Foreman Server is down.](https://github.com/CCI-MOC/rubicon-issues/issues/9)

**Comment by YonatanGolick** [comment]
[Provision the first Node 10.0.21.7 with RHCOS/RHEL OS](https://github.com/CCI-MOC/rubicon-issues/issues/11)

**Comment by YonatanGolick** [comment]
[Handle the network issues on the 2 unready nodes](https://github.com/CCI-MOC/rubicon-issues/issues/12)

**Comment by YonatanGolick** [comment]
[Create a private registry on the foreman server](https://github.com/CCI-MOC/rubicon-issues/issues/20)

**Comment by YonatanGolick** [comment]
[Download the openshift-installer](https://github.com/CCI-MOC/rubicon-issues/issues/22)

**Comment by YonatanGolick** [comment]
[Create ignition files](https://github.com/CCI-MOC/rubicon-issues/issues/23)

**Comment by YonatanGolick** [comment]
[Create RHCOS machines](https://github.com/CCI-MOC/rubicon-issues/issues/24)

**Comment by YonatanGolick** [comment]
[Get updated firmware images for the BMC + the server itself](https://github.com/CCI-MOC/rubicon-issues/issues/29)

**Comment by YonatanGolick** [comment]
[api-server not created when provisioning master node](https://github.com/CCI-MOC/rubicon-issues/issues/31)

**Comment by YonatanGolick** [comment]
Tried 4.7. 
Successfully deployed the bootstrap machine, when tried to deploy master machine got an error while the bootup:
```
Error:
Mar 29 09:58:21 systemd[1]: Failed to mount /sysroot.
-- Logs begin at Mon 2021-03-29 09:58:12 UTC, end at Mon 2021-03-29 09:58:21 UTC. --
Mar 29 09:58:21 systemd[1]: Starting Acquire live PXE rootfs image...
Mar 29 09:58:21 coreos-livepxe-rootfs[2157]: Fetching rootfs image from http://registry:8080/rhcos-4.7.0-ppc64le-live-rootfs.ppc64le.img...
Mar 29 09:58:21 coreos-livepxe-rootfs[2157]: curl: (7) Couldn't connect to server
Mar 29 09:58:21 coreos-livepxe-rootfs[2157]: Error: premature end of input data at offset 0
Mar 29 09:58:21 coreos-livepxe-rootfs[2157]: Couldn't fetch, verify, and unpack image specified by coreos.live.rootfs_url=
Mar 29 09:58:21 coreos-livepxe-rootfs[2157]: Check that the URL is correct and that the rootfs version matches the initramfs.
Mar 29 09:58:21 systemd[1]: coreos-livepxe-rootfs.service: Main process exited, code=exited, status=1/FAILURE
Mar 29 09:58:21 systemd[1]: coreos-livepxe-rootfs.service: Failed with result 'exit-code'.
Mar 29 09:58:21 systemd[1]: Failed to start Acquire live PXE rootfs image.
Mar 29 09:58:21 systemd[1]: coreos-livepxe-rootfs.service: Triggering OnFailure= dependencies.
```
We decided to go back to 4.6.22 installation because we didn't get this error on that version.

**Comment by YonatanGolick** [comment]
A general error we get almost every time we install the master node is:
```
t: address family not supported by protocol
[***   ] A start job is running for Ignition (fetch) (1min 46s / no limit)[  119.645315] ignition[2313]: GET https://api-int.ocp-cluster.domain:22623/config/master: attempt #24
[  119.689684] ignition[2313]: GET error: Get "https://api-int.ocp-cluster.domain:22623/config/master": dial tcp: lookup api-int.rubicone.ocp4.local on [::1]:53: dial udp [::1]:53: socket: address family not supported by protocol
```

This error resolves itself after a few reboots of the master node.

**Comment by YonatanGolick** [comment]
Right now we have an open case with Red Hat's support about the issue above #31

**Comment by joachimweyl** [comment]
Closing all rubicon-issues.
