### ISSUE TITLE
No Connection to the nodes

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#33]

**Comment by YonatanGolick** [comment]
Hey @naved001, 
I can't reach any of the project nodes, and When I try to connect to the BMC web interface I get an error of Invalid username/password.
![image](https://user-images.githubusercontent.com/74144741/113135503-de40c300-922a-11eb-93a7-b367d3049ce1.png)

**Comment by naved001** [comment]
hmm, for some reason the BMC of bu-21-1 and bu-21-10 had lost their configuration due to the data center power failure. I have restored those back and you should be able to login with the `hil` user now. 

I need to investigate what's up with 21.7

**Comment by naved001** [comment]
I cold power cycled 21.7 from the outlets, and now it's back. Login credentials are `root` and `0penBmc` (the defaults).

**Comment by YonatanGolick** [comment]
> I cold power cycled 21.7 from the outlets, and now it's back. Login credentials are `root` and `0penBmc` (the defaults).

The 21-1 and 21-10 nodes are working fine. 
Still cant do nothing with 21-7. Connecting to the BMC web interface and cant even reboot the node.

**Comment by YonatanGolick** [comment]
@naved001 any update?

**Comment by naved001** [comment]
@YonatanGolick I'll look at it today. I think that node may be screwed too; I will probably end up swapping with another one.

**Comment by YonatanGolick** [comment]
@naved001 Ok thank you

**Comment by naved001** [comment]
@YonatanGolick bu-21-7 I cold power cycled it again from the PDU. I have had it running for hours now; so I hope that this should be good now.

**Comment by YonatanGolick** [comment]
Hey @naved001, So the node is not working.. It entered emergency mode and when I rebooted it the node is not coming up.
Maybe we can just swap it with another one?

**Comment by YonatanGolick** [comment]
@naved001, Haven't heard from you, any update on the issue? I can't proceed with the installation without the bastion server.

**Comment by naved001** [comment]
Hi @YonatanGolick , sorry the delayed response but we are out of functioning power9 nodes at the moment. I am working with IBM support and some other folks at the data center to get it fixed asap.

**Comment by idanlv** [comment]
Hi @naved001, what is your timeframe for a resolution?
Anything we can do to help this move forward?

**Comment by idanlv** [comment]
@naved001 - following our slack chat, can you please update?

**Comment by naved001** [comment]
@YonatanGolick @idanlv 

We have updated our ticket with IBM so that they can proceed to send ship us the replacement NICs. Waiting to hear back from them.

**Comment by naved001** [comment]
@YonatanGolick I updated the BMC firmware of bu-21-7 and it has been running fine for now. Let's check back again tomorrow and see if the BMC is still up then I think it should good to use.

**Comment by naved001** [comment]
@YonatanGolick that node (bu-21-7) is still working, so I think it should be good to be used.

**Comment by YonatanGolick** [comment]
@naved001, checked the node, at first when using the buildroot OS ( the minimal OS on the node) everything worked fine. When tried to upload the RHEL 8 OS from the petitboot menu got an error and the cant reboot the system anymore.. No I have the same issue we had before. any suggestions?

**Comment by naved001** [comment]
@YonatanGolick let me know if bu-21-7 breaks again, we have a replacement BMC on standby.
