### ISSUE TITLE
Deploy an application to "Alex Cluster"

### ISSUE THREAD

**Issue by idanlv** [CCI-MOC/rubicon-issues#39]
As part of the HTB program

Reference:
https://github.com/open-infrastructure-labs/ops-issues/issues/41

**Comment by ipolonsk** [comment]
Successfully completed all those tasks under the same subject "application":

Deploy Application Resources & Create a Placement Rule
Modify a Placement Rule
Update Application Version
Deploy an application to multiple clusters at once
Didn't have any special issues.
