### ISSUE TITLE
Assisted installer attempt

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#43]
Trying to deploy openshift cluster using the assisted installer. Working with Nir on this.

**Comment by YonatanGolick** [comment]
Trying to deploy the assisted on the foreman VM.. Had some issues with storage that was solved with the help of @naved001.
Now the assisted is running and we need to generate a full discovery image to proceed with the installation.
Nirs youtube assisted installer guide https://www.youtube.com/watch?v=hz2GFxPzAOM

**Comment by joachimweyl** [comment]
Closing all rubicon-issues.
