### ISSUE TITLE
Get the ISO file for RHEL/RHCOS that suits the ppc architecture

### ISSUE THREAD

**Issue by YonatanGolick** [CCI-MOC/rubicon-issues#6]
Hey @idanlv we don't have subscription to download the ISO file for RHEL/RHCOS for the IBM power servers architecture.
As a red hatter can you help me the right subscription ? Because my only option right now is to purchase this subscription.
![Screenshot 2020-12-09 130612](https://user-images.githubusercontent.com/74144741/101625444-145ffa00-3a24-11eb-8c0d-dcd355a35a7d.png)

**Comment by idanlv** [comment]
@naved001 Can you please help us with the subscription details for the MOC?

@ipolonsk In the meantime, can you please work with Oren and Alex to help with the required ISOs?

**Comment by YonatanGolick** [comment]
Got the ISO from Oren and Ilana thank you.
